/* Định nghĩa các TAB của trang Cài đặt (mỗi mục = 1 bảng danh mục / cấu hình).
   usedIn = NƠI THAM CHIẾU danh mục/cấu hình này (hiển thị thành ghi chú "Dùng ở" để dễ hiểu). */
export const CFG_GROUPS = [
  { key: "locations", label: "Địa điểm", hint: "depot, cảng, ICD, KCN — dùng cho Tuyến · thêm ký hiệu viết tắt; tự thêm khi import bảng giá (cột FROM + TO)", ph: "VD: Cảng Tân Vũ", coded: true, codeKey: "locationCode", codeNameLabel: "Tên địa điểm", allowDupCode: true, usedIn: "Lô hàng (Nơi lấy / Nơi hạ / Nơi hạ sà lan) · Bảng giá (FROM/TO) · Lộ trình · Báo cáo (sản lượng theo tuyến)" },
  { key: "customers", label: "Khách hàng", hint: "quản lý khách hàng — MST, liên hệ, hạn thanh toán, ghi chú…", ph: "VD: Canon Vietnam", usedIn: "Lô hàng (cột Khách hàng) · Bảng giá (mỗi khách 1 bảng giá) · Bảng kê khách" },
  { key: "contTypes", label: "Loại container", hint: "dùng cho cột Cont", ph: "VD: 40HC", usedIn: "Lô hàng (cột Loại cont) · suy loại sà lan DRY/NOR theo loại cont" },
  { key: "warehouses", label: "Kho", hint: "kho hàng — dùng cho lô (chọn tối đa 3) · 1 ký hiệu có thể nhiều tên kho; có địa chỉ + ghi chú (địa chỉ đóng hàng) + tọa độ; tự thêm khi import bảng giá (cột TO)", ph: "VD: Kho A2", coded: true, codeKey: "warehouseCode", codeNameLabel: "Tên kho", addressed: true, noted: true, geo: true, allowDupCode: true, usedIn: "Lô hàng (chọn Kho ≤3) · Bảng giá (TO) · Lộ trình (gom theo kho) · Báo cáo (sản lượng theo kho) · Xuất Excel lô hàng (ghi chú → cột Địa chỉ đóng hàng)" },
  { key: "payers", label: "Bên thanh toán", hint: "dùng cho mọi dòng chi phí", ph: "VD: Tài xế", usedIn: "Lô hàng → popup Chi phí & Doanh thu (cột Bên thanh toán mỗi dòng)" },
  { key: "costItems", label: "Khoản chi phí", hint: "gắn màu “theo dõi” cho khoản cần nhắc khi chưa điền số tiền — dùng chung cho mọi lô; cờ tự hiện + VAT%", ph: "VD: Phí cân xe", colored: true, usedIn: "Lô hàng → popup Chi phí (chọn Khoản) · Báo cáo chi phí (nhóm theo khoản)" },
  { key: "choHoItems", label: "Khoản thu/chi hộ", hint: "dùng cho mục Thu chi hộ ở cả Chi phí & Doanh thu · có đơn giá mặc định", ph: "VD: Nâng", priced: true, usedIn: "Lô hàng → popup Chi phí (Chi hộ) & Doanh thu (Thu hộ)" },
  { key: "revItems", label: "Khoản doanh thu", hint: "dùng cho mục Doanh thu · có đơn giá mặc định", ph: "VD: Doanh thu cước xe", priced: true, usedIn: "Lô hàng → popup Doanh thu · Báo cáo (doanh thu)" },
  { key: "vehicles", label: "Biển số xe", hint: "đội xe — mỗi biển số chọn Xe MBF hay Xe ngoài", ph: "VD: 15C-123.45", fleet: true, usedIn: "Lô hàng (BKS vào/ra) · Quản lý xe · Phí xe nội bộ / Kỳ lương · Lộ trình · GPS" },
  { key: "drivers", label: "Lái xe", hint: "hồ sơ tài xế — SĐT (nhiều số), ngày sinh, ngày vào công ty (tự tính thâm niên), tài khoản ngân hàng, tài liệu CCCD/bằng lái", ph: "VD: A.Tuấn", drivers: true, usedIn: "Lô hàng (Tài xế) · Lộ trình (chi cho lái) · Phí xe / Kỳ lương lái xe · Yêu cầu chi (link công khai)" },
  { key: "salaryItems", label: "Khoản lương (lái xe)", hint: "các khoản lương thêm (thưởng, phụ cấp…) — chọn ở Phí xe nội bộ thay vì nhập tay để sau tổng hợp lương dễ", ph: "VD: Thưởng chuyên cần", usedIn: "Phí xe nội bộ / Kỳ lương lái xe (khoản lương phát sinh)" },
  { key: "extVendors", label: "Đơn vị xe ngoài", hint: "nhà xe thuê ngoài — chọn khi lô 'Thuê xe ngoài'; dùng cho Bảng kê xe ngoài (công nợ theo nhà xe)", ph: "VD: Nhà xe Minh Phát", usedIn: "Lô hàng (tích Thuê xe ngoài → chọn Nhà xe) · Bảng kê xe ngoài (công nợ theo nhà xe)" },
  { key: "vehicleCostTypes", label: "Loại chi phí xe", hint: "loại chi phí bảo dưỡng/sửa chữa xe — chọn ở Quản lý xe (tab Chi phí) để nhóm báo cáo theo loại", ph: "VD: Bảo dưỡng định kỳ", usedIn: "Quản lý xe → tab Chi phí (phiếu chi của XE) · Định mức km · Báo cáo chi phí (nhóm “Chi phí xe · …”)" },
  { key: "assetCategories", label: "Loại tài sản", hint: "phân loại tài sản (máy móc, thiết bị, nhà xưởng…) — chọn khi thêm/sửa tài sản ở Quản lý tài sản", ph: "VD: Máy móc thiết bị", usedIn: "Quản lý tài sản (chọn Loại khi thêm/sửa tài sản)" },
  { key: "assetCostTypes", label: "Loại chi phí tài sản", hint: "loại chi phí của tài sản (bảo trì, sửa chữa, vật tư…) — chọn ở Quản lý tài sản (tab Chi phí) để nhóm báo cáo theo loại", ph: "VD: Bảo trì, bảo dưỡng", usedIn: "Quản lý tài sản → tab Chi phí (phiếu chi của TÀI SẢN) · Báo cáo chi phí (nhóm “Chi phí tài sản · …”)" },
  { key: "payMethods", label: "Hình thức thanh toán", hint: "hình thức/tài khoản chi cho phiếu chi xe & tài sản (Chuyển khoản, Tiền mặt, Vietinbank, Bank công ty, Cá nhân…) — chọn khi duyệt thanh toán, sau lọc theo hình thức", ph: "VD: Vietinbank công ty", usedIn: "Quản lý xe & Tài sản → tab Chi phí (ô Hình thức khi duyệt/sửa phiếu) · Quản lý chi phí" },
  { key: "routeFees", label: "Phí tuyến đường", hint: "định mức phí & dầu cho từng tuyến (tập kho) — vé trạm, tiền đường, trợ cấp, phí khác, lương CRU, km, dầu 2 cầu/1 cầu", ph: "", routefees: true, usedIn: "Lộ trình (tự tính chi cho lái theo tuyến) · Phí xe nội bộ · Báo cáo chi phí" },
  { key: "fuelPrices", label: "Bảng giá dầu", hint: "đơn giá dầu (đồng/lít) theo khoảng ngày — link tính tiền dầu cho tuyến theo ngày của lô", ph: "", fuelprices: true, usedIn: "Lộ trình / Phí tuyến (tính tiền dầu theo ngày của lô)" },
  { key: "__general", label: "Cấu hình chung", hint: "cấu hình dùng chung cho hệ thống — VAT mặc định, ngưỡng Free time… (mở rộng thêm sau)", general: true, usedIn: "VAT mặc định → Bảng kê khách · Free time → Lô hàng · Ngưỡng cảnh báo hạn → Quản lý xe" },
];
